### ISSUE TITLE
Network API breaks

### ISSUE THREAD

**Issue by thecatcore** [LegacyRewoven/rewoven-api#27]
`[18:17:50] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:45) [client-intermediary.jar:?]
	at net.minecraft.class_1600.method_2916(class_1600.java:881) [client-intermediary.jar:?]
	at net.minecraft.class_1600.method_5580(class_1600.java:325) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:124) [client-intermediary.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1187) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1170) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:570) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at net.minecraft.class_1967.readByte(class_1967.java:609) ~[client-intermediary.jar:?]
	at net.minecraft.class_1967.method_7419(class_1967.java:109) ~[client-intermediary.jar:?]
	at net.minecraft.class_1967.method_7427(class_1967.java:235) ~[client-intermediary.jar:?]
	at net.minecraft.class_1845.method_7569(class_1845.java:1291) ~[client-intermediary.jar:?]
	at net.minecraft.class_2015.method_7732(class_2015.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_2015.method_1831(class_2015.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:44) ~[client-intermediary.jar:?]
	... 18 more
[18:17:51] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:45) [client-intermediary.jar:?]
	at net.minecraft.class_1600.method_2916(class_1600.java:881) [client-intermediary.jar:?]
	at net.minecraft.class_1600.method_5580(class_1600.java:325) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:124) [client-intermediary.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[netty-all-4.0.23.Final.jar:4.0.23.Final]
	at net.minecraft.class_1967.release(class_1967.java:979) ~[client-intermediary.jar:?]
	at net.minecraft.class_1845.method_7569(class_1845.java:1288) ~[client-intermediary.jar:?]
	at net.minecraft.class_2015.method_7732(class_2015.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_2015.method_1831(class_2015.java:9) ~[client-intermediary.jar:?]
	at net.minecraft.class_2570$1.run(class_2570.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at net.minecraft.class_1723.method_10652(class_1723.java:44) ~[client-intermediary.jar:?]
	... 18 more`

**Comment by PseudoDistant** [comment]
wat

**Comment by thecatcore** [comment]
that's the error that appears when looking at "empty" villager trades, or connect to hypixel for example.

**Comment by thecatcore** [comment]
Doesn't happen if network module is excluded

**Comment by PseudoDistant** [comment]
Yes, that's the issue I had earlier...

The one that you closed and marked fixed...

**Comment by PseudoDistant** [comment]
Or rather, it's caused by that, or is related to that.

At least I think so, that's all I could really gather from debugging it.
Maybe I didn't debug properly.

**Comment by PseudoDistant** [comment]
Fak

**Comment by Domaman202** [comment]
can i get instructions for getting this error?
